{% set github_owner = "pycontribs" %}
{% set name = "wstools" %}
{% set version = "0.4.8" %}
{% set sha256 = "8d62b402b53e72975dada1863f2a55ca62487147d79889924f3d8c6548354581" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ github_owner }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [ not py2k or win ]
  script: PBR_VERSION=${PKG_VERSION} && export PBR_VERSION && python setup.py install --single-version-externally-managed --record record.txt 

requirements:
  build:
    - python
    - pbr
    - pytest-runner
    - setuptools
  run:
    - python
    - six
    - pbr

test:
  imports:
    - wstools
    - wstools.c14n
    - wstools.MIMEAttachment
    - wstools.Namespaces
    - wstools.TimeoutSocket
    - wstools.UserTuple
    - wstools.Utility
    - wstools.WSDLTools
    - wstools.XMLname
    - wstools.XMLSchema

about:
  home: https://github.com/pycontribs/wstools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'WSDL parsing services package for Web Services for Python'
  dev_url: https://github.com/pycontribs/wstools

extra:
  recipe-maintainers:
    - pvanheus
    - AjitPS
