travis:
  secure:
    BINSTAR_TOKEN: Cy1tlekJV7iluVoMpNT7gjWu1OjxxbD496k5rlN3j9+tVcQDt5KV9pkrue4liU9Yyj5xvE8le7yNu7RhaebTroCjoaJXAlnztp0I2YGAa1zVuCt1pdE7J5G4Yk4s2tDPPUp9/dw9U/jujv4SFmMrzW9cXXChhwgQTXVPOTqu5BVTbV88BK/NfnWy6AOJ/giekLxiuBcRRjnUbTTgfxhxfrjexNPXCu9dwBaccqjXfaUpGC5TftTko6E/X60cHi3ahK+Na8O+6piZUkz0fLALXJmPCIZkJw2l0fF9abFZuhdrymdq5LGqLVAV5MR1j+7ZGbkyuQmp2vGqz8O1k7M1anpg2RvJFStZobdb9k6r0zkywtQ2JOdtSGF8a8Gh3YdsCFz0U10QaKx1fk9zsxa+CI/ILmJcUVN4QOvetLqvLm/R13lxDUF3uMdATPz2pPmGTtvXWu7zQr9T5hrD0pmv7bFedpizkdiMOyb4mKpx7L1mdWJdneii/MLi9+8J9TCMXE1VeryypWrtxNnx3WIPaYtH2YL4OadTWsLsb40Bp5bhd1qou20TPm7cW2ilDUFhVmhSgGJpgUJjpZh15lRSMTD/xwKwQxaZLidB5tCjZuZVtF9OL5uvNq4ONY6JNNjLPCgNW62xO/vjbHJ800th3JwqRqVsn+G7b8BnOg60TKY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
